#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Disable forward/back buttons
##?
##? Usage:
##?    -
docs::parse "$@"

xinput

xinput set-button-map 15 1 2 3 4 5 6 7 0 0
